#!/usr/bin/env php
<?php

use Phalcon\DI\FactoryDefault\CLI,
	Danzabar\CLI\Application,
	Phalcon\Loader;
	
/**
 * 
 * Create a new DI for the console
 *
 */
$di = new CLI;


/**
 * Register the loader for the commands 
 *
 */
$loader = new Loader;
$loader->registerDirs(
	array(
		__DIR__ . '/app/commands'
	)
);
$loader->register();


/**
 *  Add the Cli config file.
 *
 */
$config = require_once __DIR__ . '/app/config/cli.php';
$di->set('config', $config);

/**
 * Load the web app DI, so we have access to DB and all website functionality.
 *
 */
$webapp = require_once __DIR__ . '/bootstrap/environment.php';
$di->set('application', $webapp);


$app = new Application;
$app->setDI($di);

try {
	
	$app->start($argv);
		
} catch(\Exception $e) {
	echo $e->getMessage()."\n";
	exit(255);
}

?>
